<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<!--<PublishAot>true</PublishAot>-->
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Amazon.Lambda.AspNetCoreServer.Hosting" Version="2.1.0" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.9" />
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.9" />
		<PackageReference Include="Microsoft.OpenApi" Version="2.7.5" />
		<PackageReference Include="Scalar.AspNetCore" Version="2.16.6" />
		<PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\GastosApp.Application\GastosApp.Application.csproj" />
		<ProjectReference Include="..\GastosApp.Infrastructure\GastosApp.Infrastructure.csproj" />
	</ItemGroup>

</Project>
