<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\GastosApp.Application\GastosApp.Application.csproj" />
    <ProjectReference Include="..\GastosApp.Domain\GastosApp.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.CognitoIdentityProvider" Version="4.0.10.1" />
    <PackageReference Include="AWSSDK.SecretsManager" Version="4.0.5.8" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.9" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
